machine:
  services:
    - docker

dependencies:
  override:
    - docker build -t russellknox/ukvi_service_options .

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push russellknox/team-health-app-response    
  staging:
    branch: dev
    commands:
      - docker login --email=$HEROKU_EMAIL --username=$HEROKU_USER --password=$(heroku auth:token) registry.heroku.com
      - docker tag russellknox/ukvi_service_options  registry.heroku.com/stay-in-the-uk/web
      - docker push registry.heroku.com/stay-in-the-uk/web